<?php

namespace SynergyERP\Shared\Contracts\Commands;

use SynergyERP\Shared\Contracts\Contract;
use SynergyERP\Shared\ManifestLoader;
use SynergyERP\Shared\ManifestParser;
use SynergyERP\Shared\Models\Operations\OperationKeyContext;
use SynergyERP\Shared\Services\AuthServiceUlidClient;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Command Contract class
 * 
 * @author Alexander Torres
 * @package SynergyERP\Shared\Contracts\Commands
 */
class BaseCommandContract extends Contract
{
    /**
     * Constructor for the CommandContract
     *
     * @param array $requestData
     * @param string $tenantSchema
     * @param OperationKeyContext|null $operationKeyContext
     * @param string|null $principalPuid  Authenticated principal's public_id
     *                                    (from the JWT). Forwarded so
     *                                    beforeValidation() can inject
     *                                    `created_by_principal` when a
     *                                    concrete contract marks it required.
     */
    public function __construct(
        array $requestData,
        string $tenantSchema,
        ?OperationKeyContext $operationKeyContext = null,
        ?string $principalPuid = null
    ) {
        parent::__construct($requestData, $tenantSchema, $operationKeyContext, $principalPuid);
    }

    /** @Override */
    protected function rules(): array
    {
        $modelName = $this->extractModelNameFromClass();
        $action = $this->getAction();
        
        $manifestLoader = ManifestLoader::load();
        $manifest = $manifestLoader->getManifest();
        $manifestParser = new ManifestParser($manifest);
        $rules = $manifestParser->generateRules($manifest['models'][$modelName], $action, $this->getTenantSchema(), $modelName);
        return $rules;
    }

    /**
     * Inject server-generated identifier columns into $this->requestData
     * BEFORE validation runs, so hardcoded-`required` rules in concrete
     * create contracts pass instead of 422-ing.
     *
     * Handled here (vs afterValidation) because of a lifecycle ordering
     * problem: the abstract Contract::__construct calls validate() before
     * any post-validation hook, so any rule that lists public_id /
     * public_ref / version as required rejects the request before we can
     * fill them in.
     *
     * @return void
     */
    protected function beforeValidation(): void
    {
        if ($this->getAction() !== 'create') {
            return;
        }

        // Manifest-declared defaults. Any fillable column whose manifest
        // entry carries a `default` and whose request payload is missing
        // or null gets that default injected here. Pairs with the
        // ManifestParser change that emits a `nullable` rule whenever a
        // default exists — together they implement the laf-web contract:
        //   fillable + default  →  optional on the wire, auto-assigned
        //   on create when the client doesn't supply a value.
        $this->fillManifestDefaults();

        // Server-generated external refs. The contract intentionally does
        // not accept public_id / public_ref / version / ulid from the
        // client — they're populated here so the request body never has
        // to know about them.
        $this->fillServerGeneratedRefs();

        // Audit columns. Concrete override contracts (generated by LAF)
        // often mark `created_at` / `created_by_principal` as `required`
        // even though they're server-owned. Inject them here — only when
        // missing AND the active rules actually require them — so the
        // client never has to manage server-scoped audit state.
        $this->fillAuditCreatedAt();
        $this->fillAuditCreatedBy();
    }

    /**
     * Audit timestamp injection. When the active rules mark `created_at`
     * required and the client didn't send one, stamp the request with the
     * current server-time in MySQL datetime shape. Lives at the contract
     * layer instead of the model/DB default because concrete override
     * contracts validate before the INSERT ever runs.
     */
    protected function fillAuditCreatedAt(): void
    {
        foreach (['created_at'] as $field) {
            if (!$this->isFieldRequiredByRules($field)) {
                continue;
            }
            if (!empty($this->requestData[$field])) {
                continue;
            }
            $this->requestData[$field] = date('Y-m-d H:i:s');
        }
    }

    /**
     * Audit principal injection. Stamp `created_by_principal` /
     * `created_by` from the JWT-extracted principal whenever the
     * manifest declares the field on this model — irrespective of
     * whether the wire validation rules marked it required. The DB may
     * require the column (NOT NULL, no default) even when the client
     * contract does not, so gating on validation alone is wrong.
     *
     * Value resolution: when the manifest declares `relationship.member`
     * as `"id"` (BIGINT FK to Principal.id), look up the principal's
     * integer id from the puid. Otherwise fall back to the puid for
     * legacy columns that still reference Principal.public_id.
     *
     * No-op if the contract was instantiated without a principal
     * (anonymous call, legacy test).
     */
    protected function fillAuditCreatedBy(): void
    {
        $puid = $this->getPrincipalPuid();
        if ($puid === null) {
            return;
        }
        $modelData = $this->getCurrentModelData();
        $members = $modelData['members'] ?? [];

        $resolvedId = null;
        foreach (['created_by_principal', 'created_by'] as $field) {
            if (!isset($members[$field])) {
                continue;
            }
            if (!empty($this->requestData[$field])) {
                continue;
            }
            $member = $members[$field]['relationship']['member'] ?? null;
            if ($member === 'id') {
                if ($resolvedId === null) {
                    $resolvedId = self::resolvePrincipalIdFromPuid($puid);
                }
                if ($resolvedId !== null) {
                    $this->requestData[$field] = $resolvedId;
                }
            } else {
                $this->requestData[$field] = $puid;
            }
        }
    }

    /**
     * Resolve a Principal.public_id (CHAR(26) ULID) to its BIGINT id.
     * Static so the matching helper in BaseCommandHandler can share the
     * lookup without duplicating the query. Caches the result per
     * request to avoid repeating the SELECT on chained creates.
     */
    public static function resolvePrincipalIdFromPuid(string $puid): ?int
    {
        static $cache = [];
        if (array_key_exists($puid, $cache)) {
            return $cache[$puid];
        }
        try {
            $manifest = ManifestLoader::load()->getManifest();
            $principal = $manifest['models']['Principal'] ?? null;
            $schema = $principal['eloquent']['schema'] ?? 'accounts';
            $table = $principal['eloquent']['table'] ?? 'principals';
            $row = DB::connection('mysql')
                ->table("{$schema}.{$table}")
                ->where('public_id', $puid)
                ->first(['id']);
            $cache[$puid] = $row ? (int) $row->id : null;
        } catch (\Throwable $e) {
            $cache[$puid] = null;
        }
        return $cache[$puid];
    }

    /**
     * Does the contract's active rules array list `$field` as required?
     * Supports both array-of-rules ("required|string|max:26" is split by
     * Laravel; concrete contracts sometimes use the pipe form, sometimes
     * an array — handle both).
     */
    private function isFieldRequiredByRules(string $field): bool
    {
        $rules = $this->rules();
        $rule = $rules[$field] ?? null;
        if ($rule === null) {
            return false;
        }
        if (is_array($rule)) {
            return in_array('required', $rule, true);
        }
        if (is_string($rule)) {
            $parts = explode('|', $rule);
            return in_array('required', $parts, true);
        }
        return false;
    }

    /**
     * Inject manifest-declared defaults into $this->requestData for any
     * fillable column the client didn't supply. Runs only on create;
     * update semantics treat a client-sent null as an explicit clear.
     *
     * Skips SQL function literals (e.g. `CURRENT_TIMESTAMP`) — those
     * belong to the DB column definition, not the PHP request payload.
     * Timestamp columns are already private-visibility and excluded from
     * rules by the manifest parser, but this guard is cheap belt-and-
     * suspenders.
     */
    protected function fillManifestDefaults(): void
    {
        $modelData = $this->getCurrentModelData();
        if ($modelData === null) {
            return;
        }
        $members = $modelData['members'] ?? [];

        foreach ($members as $fieldName => $meta) {
            if (!($meta['eloquent']['fillable'] ?? false)) {
                continue;
            }
            $default = $meta['default'] ?? null;
            if ($default === null || $default === '') {
                continue;
            }
            if (is_string($default) && strtoupper($default) === 'CURRENT_TIMESTAMP') {
                continue;
            }
            if (!array_key_exists($fieldName, $this->requestData)
                || $this->requestData[$fieldName] === null) {
                $this->requestData[$fieldName] = $this->coerceDefaultLiteral(
                    $default,
                    $meta['type'] ?? null,
                );
            }
        }
    }

    /**
     * Coerce a manifest-declared default literal into the PHP value Eloquent
     * can bind cleanly. Manifests carry SQL DDL-style string literals (e.g.
     * `'TRUE'`, `'0'`, `'1'`) for boolean/integer defaults; if we hand those
     * straight to Eloquent the prepared statement ships them as strings and
     * MySQL strict mode rejects (`Incorrect integer value: 'TRUE' for column
     * is_active`). Map BOOLEAN/TINYINT(1) to bool, integer types to int, and
     * fall through unchanged for everything else.
     */
    private function coerceDefaultLiteral(mixed $default, ?string $sqlType): mixed
    {
        if (!is_string($sqlType)) {
            return $default;
        }
        $upperType = strtoupper($sqlType);
        $isBool = $upperType === 'BOOLEAN'
            || $upperType === 'BOOL'
            || $upperType === 'TINYINT(1)';
        if ($isBool) {
            if (is_bool($default)) return $default;
            if (is_int($default)) return $default !== 0;
            if (is_string($default)) {
                $u = strtoupper($default);
                if ($u === 'TRUE' || $u === '1') return true;
                if ($u === 'FALSE' || $u === '0') return false;
            }
            return $default;
        }
        // Crude check for integer family — covers TINYINT, SMALLINT, INT,
        // BIGINT, MEDIUMINT, with or without (n) length spec. Decimal /
        // numeric default to native parse downstream.
        if (preg_match('/^(TINY|SMALL|MEDIUM|BIG)?INT\b/', $upperType) === 1) {
            if (is_int($default) || is_bool($default)) return (int) $default;
            if (is_string($default) && preg_match('/^-?\d+$/', $default) === 1) {
                return (int) $default;
            }
        }
        return $default;
    }

    /**
     * Handle manual increment fields after validation
     *
     * @return void
     */
    protected function afterValidation(): void
    {
        if ($this->getAction() !== 'create') {
            return;
        }

        // Server-owned identity columns. Every create gets a fresh
        // public_id minted by the auth-service and a prefix-based
        // public_ref of the form `{PREFIX}_{7 uppercase alnum}`. These
        // are unconditional — the API never accepts client-supplied
        // values, and the manifest parser already strips both fields
        // from the create rules so $validator->validated() drops them.
        $this->mintServerIdentity();

        // ManifestParser skips ulid on create, so $validator->validated()
        // strips it even though beforeValidation() populated it in
        // $requestData. Copy it back so the handler, which fills the
        // model from $validatedData, sees the injected value. Same for
        // `version` — its manifest entry is nullable: false with no
        // default, so it doesn't appear in validated() output either
        // when the server generates it.
        foreach (['ulid', 'version'] as $field) {
            if (
                !array_key_exists($field, $this->validatedData)
                && array_key_exists($field, $this->requestData)
            ) {
                $this->validatedData[$field] = $this->requestData[$field];
            }
        }

        // Transition-window passthrough: any request-data key that matches
        // a fillable manifest member but wasn't emitted as a rule (e.g.
        // because the LAF-regenerated TS schema / PHP manifest haven't
        // caught up yet) gets carried from $requestData into
        // $validatedData here. Mirrors the defineModel.create()
        // passthrough on the frontend. Laravel's $fillable gate on the
        // Eloquent model remains authoritative — over-including here is
        // safe because non-fillable columns never make it into the INSERT.
        $modelData = $this->getCurrentModelData();
        if ($modelData !== null) {
            foreach (($modelData['members'] ?? []) as $fieldName => $meta) {
                if (!($meta['eloquent']['fillable'] ?? false)) {
                    continue;
                }
                if (array_key_exists($fieldName, $this->validatedData)) {
                    continue;
                }
                if (!array_key_exists($fieldName, $this->requestData)) {
                    continue;
                }
                $this->validatedData[$fieldName] = $this->requestData[$fieldName];
            }
        }

        $manualIncrementFields = $this->getManualIncrementFields();

        foreach ($manualIncrementFields as $fieldName => $fieldConfig) {
            if (isset($this->validatedData[$fieldName])) {
                continue;
            }
            
            $tableName = $fieldConfig['table'];
            $defaultValue = $fieldConfig['default'] ?? 0;
            // $lockKey = "manual_increment:{$this->getTenantSchema()}:{$tableName}:{$fieldName}";
            
            // $lock = Cache::lock($lockKey, 10);
            
            // try {
            //     $lock->block(5);
                $qualifiedTableName = "{$this->getTenantSchema()}.{$tableName}";
                $maxValue = DB::connection('mysql')->table($qualifiedTableName)
                    ->max($fieldName);
                $this->validatedData[$fieldName] = $maxValue ? $maxValue + 1 : 1;
            // } finally {
            //     $lock->release();
            // }
        }
    }

    /**
     * Populate server-owned ULID and row-version columns when the model
     * declares them, and seed placeholder values for public_id / public_ref
     * so concrete contracts that hardcode `required` rules don't 422 before
     * afterValidation() can mint the authoritative values.
     *
     * The placeholders here are intentionally throwaway — mintServerIdentity()
     * in afterValidation() overwrites them with an auth-service-minted ULID
     * and a `{prefix}_{7-char alnum}` public_ref. Both seed values are 26-char
     * ULID-shaped strings so they satisfy the common LAF-generated rules
     * (`required`, `string`, `max:26`, `size:26`) without needing per-rule
     * inspection.
     *
     * Mutates $this->requestData (not $this->validatedData) because this
     * helper runs in beforeValidation(), so the validator sees the
     * generated values and `required` rules pass.
     */
    protected function fillServerGeneratedRefs(): void
    {
        $modelData = $this->getCurrentModelData();
        if ($modelData === null) {
            return;
        }
        $members = $modelData['members'] ?? [];

        // Placeholder seeds — the validator just needs *something* here.
        // mintServerIdentity() (afterValidation) will replace these with
        // auth-service-minted / prefix-based values before the handler
        // sees the data.
        if (isset($members['public_id']) && empty($this->requestData['public_id'])) {
            $this->requestData['public_id'] = (string) Str::ulid();
        }
        if (isset($members['public_ref']) && empty($this->requestData['public_ref'])) {
            $this->requestData['public_ref'] = (string) Str::ulid();
        }

        if (isset($members['ulid']) && empty($this->requestData['ulid'])) {
            $this->requestData['ulid'] = (string) Str::ulid();
        }

        // Row version: INT, typically NOT NULL, no default. When the
        // manifest declares a non-nullable `version` column and the
        // client didn't send one, start at 1. Later updates (update
        // contracts) bump this via their own concurrency logic — we
        // only seed it on create.
        if (
            isset($members['version'])
            && !($members['version']['isNullable'] ?? true)
            && !isset($this->requestData['version'])
        ) {
            $this->requestData['version'] = 1;
        }
    }

    /**
     * Mint the canonical server identity for a freshly-created record:
     *
     *   - public_id ← a ULID issued by the auth-service (the system-wide
     *     ULID authority). Falls back to a local Str::ulid() with a
     *     warning log if the auth-service is unreachable, so contracts
     *     never block on transient infrastructure issues.
     *   - public_ref ← `{prefix}_{7-char uppercase alnum}` where the
     *     prefix is the model's manifest-declared `eloquent.prefix`
     *     (frontend-injected via service-manifest-net). The 7-char
     *     suffix is generated and re-rolled until it's unique within
     *     the model's tenant table.
     *
     * Both columns are skipped only when the model's manifest doesn't
     * declare them — e.g. internal join tables. Existing values in
     * $validatedData / $requestData are overwritten because these fields
     * are server-owned and the API contract is "client never supplies".
     */
    protected function mintServerIdentity(): void
    {
        $modelData = $this->getCurrentModelData();
        if ($modelData === null) {
            return;
        }
        $members   = $modelData['members'] ?? [];
        $eloquent  = $modelData['eloquent'] ?? [];
        $tableName = $eloquent['table'] ?? strtolower($this->extractModelNameFromClass());

        if (isset($members['public_id'])) {
            $publicId = AuthServiceUlidClient::mint();
            $this->validatedData['public_id'] = $publicId;
            $this->requestData['public_id']   = $publicId;
        }

        if (isset($members['public_ref'])) {
            $publicRef = $this->buildPublicRef($eloquent, $tableName);
            $this->validatedData['public_ref'] = $publicRef;
            $this->requestData['public_ref']   = $publicRef;
        }
    }

    /**
     * Build a `{PREFIX}_{7-char uppercase alnum}` public_ref. PREFIX comes
     * from the manifest at `eloquent.prefix` (frontend-injected via
     * service-manifest-net's modelPrefixes utility). When the manifest
     * doesn't carry a prefix, fall back to the first three letters of
     * the model name so we never emit an empty `_XXXXXXX` ref.
     *
     * Uniqueness: the 7-char suffix is re-rolled until no row in the
     * tenant's table carries the same public_ref. The probe is best-
     * effort — wrapped in a try/catch so an unbootable DB (unit tests,
     * pre-migration boot) degrades to "first roll wins" rather than
     * crashing the contract.
     */
    private function buildPublicRef(array $eloquent, string $tableName): string
    {
        $prefix = $eloquent['prefix'] ?? null;
        if (!is_string($prefix) || $prefix === '') {
            $modelName = $this->extractModelNameFromClass() ?: 'OBJ';
            $prefix    = strtoupper(substr(preg_replace('/[^A-Za-z]/', '', $modelName), 0, 3));
            $prefix    = str_pad($prefix, 3, 'X');
        } else {
            $prefix = strtoupper($prefix);
        }

        $qualified = "{$this->getTenantSchema()}.{$tableName}";
        $maxAttempts = 8;

        for ($attempt = 0; $attempt < $maxAttempts; $attempt++) {
            $candidate = "{$prefix}_" . $this->randomAlnumSuffix(7);

            try {
                $exists = DB::connection('mysql')
                    ->table($qualified)
                    ->where('public_ref', $candidate)
                    ->exists();
            } catch (\Throwable) {
                return $candidate;
            }

            if (!$exists) {
                return $candidate;
            }
        }

        // Extremely unlikely (36^7 ≈ 78B combinations); ship the last
        // candidate rather than blocking the create. A unique index on
        // public_ref will catch true collisions at the DB layer.
        return $candidate;
    }

    /**
     * Generate a $length-char string drawn from [A-Z0-9]. Uses random_int
     * (CSPRNG) rather than mt_rand so collisions stay statistically
     * uniform across tenants and processes.
     */
    private function randomAlnumSuffix(int $length): string
    {
        $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $max      = strlen($alphabet) - 1;
        $out      = '';
        for ($i = 0; $i < $length; $i++) {
            $out .= $alphabet[random_int(0, $max)];
        }
        return $out;
    }

    /**
     * Resolve the current model's manifest entry, or null if unresolvable.
     */
    protected function getCurrentModelData(): ?array
    {
        $modelName = $this->extractModelNameFromClass();
        if (!$modelName) {
            return null;
        }
        $manifest = ManifestLoader::load()->getManifest();
        return $manifest['models'][$modelName] ?? null;
    }

    /**
     * Get manual increment fields from manifest
     *
     * @return array
     */
    private function getManualIncrementFields(): array
    {
        $manifestLoader = ManifestLoader::load();
        $manifest = $manifestLoader->getManifest();
        $modelName = $this->extractModelNameFromClass();
        
        if (!isset($manifest['models'][$modelName])) {
            return [];
        }
        
        $modelData = $manifest['models'][$modelName];
        $members = $modelData['members'] ?? [];
        $tableName = $modelData['eloquent']['table'] ?? strtolower($modelName);
        
        $manualIncrementFields = [];
        
        foreach ($members as $fieldName => $fieldData) {
            $isManualIncrement = $fieldData['isManualIncrementing'] ?? false;
            $isPrimaryKey = $fieldData['isPrimaryKey'] ?? false;
            $isFillable = $fieldData['eloquent']['fillable'] ?? false;
            
            if ($isManualIncrement && !$isPrimaryKey && $isFillable) {
                $manualIncrementFields[$fieldName] = [
                    'table' => $tableName,
                    'default' => $fieldData['default'] ?? 0
                ];
            }
        }
        
        return $manualIncrementFields;
    }

    /**
     * Extract model name from operationKeyContext or contract class name
     * 
     * @return string
     */
    private function extractModelNameFromClass(): string
    {
        // First try to get from operationKeyContext if available
        $modelName = $this->getModelName();
        if ($modelName !== null) {
            return $modelName;
        }
        
        // Fallback: try regex pattern matching on class name for custom contracts
        // Pattern: App\Contracts\Commands\{ModelName}\{Action}{ModelName}CommandContract
        $className = static::class;
        preg_match('/\\\\([A-Z][a-zA-Z]+)\\\\[A-Z][a-z]+\1CommandContract$/', $className, $matches);
        return $matches[1] ?? '';
    }
}
